---
name: Release Images

on:
  push:
    branches:
      - release-0.12
      - release-*

jobs:
  release:
    name: Release Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0

      - name: Build and release new images
        uses: submariner-io/shipyard/gh-actions/release-images@release-0.12
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
